# Generated by Django 2.2.2 on 2020-09-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20, verbose_name='管理员')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_super_admin', models.BooleanField(verbose_name='超级管理员')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20, verbose_name='店名')),
                ('address', models.TextField(verbose_name='门店地址')),
                ('phone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('open_date', models.DateField(verbose_name='开张日期')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='CredentialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.AdminInfo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.StoreInfo')),
            ],
            options={
                'verbose_name': '凭证',
                'verbose_name_plural': '凭证',
                'db_table': 'credential',
            },
        ),
    ]
