# Generated by Django 2.2.2 on 2020-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('card_number', models.CharField(max_length=6, verbose_name='会员卡号')),
                ('open_date', models.DateField(verbose_name='办理日期')),
                ('balance', models.FloatField(verbose_name='余额')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'member',
            },
        ),
    ]
