# Generated by Django 2.2.2 on 2020-09-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_memberinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
    ]
