# Generated by Django 2.2.2 on 2020-09-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_memberinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('gender', models.BooleanField(default=True, verbose_name='性别')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('crew_number', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='技师工号')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
            ],
            options={
                'verbose_name': '技师',
                'verbose_name_plural': '技师',
                'db_table': 'crew',
            },
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='房间名称')),
                ('bed_count', models.IntegerField(default=0, verbose_name='床位总数')),
            ],
            options={
                'verbose_name': '客房',
                'verbose_name_plural': '客房',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='服务名称')),
                ('duration', models.IntegerField(default=0, verbose_name='项目时常')),
                ('price', models.IntegerField(default=0, verbose_name='项目费用')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='SpendingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='支出明细')),
                ('amount', models.IntegerField(default=0, verbose_name='支出费用')),
                ('spend_date', models.DateField(verbose_name='流水时间')),
            ],
            options={
                'verbose_name': '日常开支',
                'verbose_name_plural': '日常开支',
                'db_table': 'spending',
            },
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='admin_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='card_number',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='会员卡号'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='name',
            field=models.CharField(max_length=8, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='address',
            field=models.TextField(unique=True, verbose_name='门店地址'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='store_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='店名'),
        ),
    ]
