# Generated by Django 2.2.2 on 2020-09-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200930_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='admin_name',
            field=models.CharField(max_length=20, verbose_name='管理员'),
        ),
    ]
