# Generated by Django 2.2.2 on 2020-10-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200930_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='充值金额')),
                ('topup_date', models.DateField(verbose_name='充值时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MemberInfo')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'topup',
            },
        ),
    ]
