# Generated by Django 2.2.2 on 2020-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_topupinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spendinginfo',
            old_name='name',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='spendinginfo',
            name='spending_type',
            field=models.CharField(max_length=10, null=True, verbose_name='支出类型'),
        ),
    ]
